using System.Collections.Immutable;
using System.Text;
using System.Text.RegularExpressions;
using Humanizer;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Newtonsoft.Json;

namespace Mocale.SourceGenerators;

[Generator]
public class LocalizationKeySourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // TODO: Provide easy way to bundle as ER & Additional File
        var constants = context.AdditionalTextsProvider
            .Where(FileMatches)
            .Select((text, token) => text.GetText(token)?.ToString())
            .Where(text => text is not null)!
            .Collect<string>();

        context.RegisterSourceOutput(constants, GenerateCode);
    }

    private bool FileMatches(AdditionalText text)
    {
        var fileName = Path.GetFileNameWithoutExtension(text.Path);
        var extension = Path.GetExtension(text.Path);

        var match = Regex.IsMatch(fileName, "^[A-Za-z]{2,4}([_-][A-Za-z]{4})?([_-]([A-Za-z]{2}|[0-9]{3}))?$");

        return match && extension.Equals(".json", StringComparison.OrdinalIgnoreCase);
    }

    private static Dictionary<string, string> GetTranslationUniqueKeys(List<string> translationsJson, SourceProductionContext context)
    {
        // TODO: we need sanitized keys to to preserve the json key value...
        var uniqueKeys = new Dictionary<string, string>();

        if (translationsJson.Count < 1)
        {
            context.Report(Diagnostics.Warnings.NoLocalizationFilesDetected);
        }
        else
        {
            context.Report(Diagnostics.Information.ProcessingFiles);
        }

        foreach (var translationJson in translationsJson)
        {
            try
            {
                var translations = JsonConvert.DeserializeObject<Dictionary<string, string>>(translationJson);

                if (translations is null)
                {
                    context.Report(Diagnostics.Warnings.FileNotJsonLocalization, translationJson);
                    continue;
                }

                foreach (var translation in translations)
                {
                    var sanitizedKey = SanitizeKey(translation.Key);

                    if (!uniqueKeys.ContainsKey(sanitizedKey))
                    {
                        uniqueKeys.Add(sanitizedKey, translation.Key);
                    }
                }
            }
            catch (Exception ex)
            {
                context.Report(Diagnostics.Errors.ParsingException, ex, translationJson);
            }
        }

        return uniqueKeys;
    }

    private static string SanitizeKey(string dirtyKey)
    {
        // https://stackoverflow.com/a/11396038
        var removeChars = new HashSet<char>(" ?&^$#@!()+-,:;<>’\'-*.");
        var result = new StringBuilder(dirtyKey.Length);

        foreach (var c in dirtyKey)
        {
            if (!removeChars.Contains(c)) // prevent dirty chars
            {
                result.Append(c);
            }
        }

        return result.ToString().Pascalize();
    }

    private static void GenerateCode(SourceProductionContext context, ImmutableArray<string> translations)
    {
        var translationKeys = GetTranslationUniqueKeys(translations.ToList(), context);

        const string translationNamespace = "Mocale.Translations";

        var source = GenerateSource(translationNamespace, translationKeys);

        context.AddSource("MocaleTranslationKeys.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static string GenerateSource(string generatedNamespace, Dictionary<string, string> keysToGenerate)
    {
        // Build up the source code
        var constantTemplate = "public const string {0} = \"{1}\";";
        var commentTemplate = "/// Looks up a localized string using key {0}.";

        var formattedProperties = new Dictionary<string, string>();

        foreach (var key in keysToGenerate)
        {
            // TODO: Handle auto accessibility translations
            // if (camelKey.EndsWith("Accessibility", StringComparison.Ordinal))
            // {
            //     // Accessibility keys are automatically paired to the original keys
            //     // Aka the key: KeyOne
            //     // will be used for "{mocale:Translate {x:Static keys:KeyOne}}"
            //     // and
            //     // "{mocale:TranslateAccessibility {x:Static keys:KeyOne}}"
            //     continue;
            // }

            var template = string.Format(constantTemplate, key.Key, key.Value);

            var comment = string.Format(commentTemplate, key.Value);

            formattedProperties.Add(template, comment);
        }

        var source = $@"// <auto-generated/>
namespace {generatedNamespace};

public static class TranslationKeys
{{
";

        var sb = new StringBuilder();

        sb.Append(source);

        var i = 0;

        foreach (var property in formattedProperties)
        {
            if (i > 0)
            {
                sb.AppendLine();
                sb.AppendLine();
            }

            sb.Append(new string('\t', 1));
            sb.AppendLine("/// <summary>");
            sb.Append(new string('\t', 1));
            sb.AppendLine(property.Value);
            sb.Append(new string('\t', 1));
            sb.AppendLine("/// </summary>");
            sb.Append(new string('\t', 1));
            sb.AppendLine(property.Key);

            i++;
        }

        sb.AppendLine("}");

        return sb.ToString();
    }
}
