global using Mocale.Abstractions;
global using Mocale.Models;
global using Mocale.Providers.Azure.Blob.Abstractions;
global using Mocale.Providers.Azure.Blob.Models;
global using Microsoft.Extensions.Logging;
global using System.Globalization;
global using Ardalis.GuardClauses;
global using Azure.Storage.Blobs;
global using Azure.Storage.Blobs.Models;
