//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mocale.Samples.Resources.Resx {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.1.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Mocale.Samples.Resources.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CurrentLocaleName {
            get {
                return ResourceManager.GetString("CurrentLocaleName", resourceCulture);
            }
        }
        
        internal static string LocalizationCurrentProviderIs {
            get {
                return ResourceManager.GetString("LocalizationCurrentProviderIs", resourceCulture);
            }
        }
        
        internal static string LocalizationProviderName {
            get {
                return ResourceManager.GetString("LocalizationProviderName", resourceCulture);
            }
        }
        
        internal static string MocaleDescription {
            get {
                return ResourceManager.GetString("MocaleDescription", resourceCulture);
            }
        }
        
        internal static string MocaleTitle {
            get {
                return ResourceManager.GetString("MocaleTitle", resourceCulture);
            }
        }
    }
}
