name: Mocale Release

on:
  workflow_dispatch:
    inputs:
      artifact-name:
        type: string
        description: The name of the artifact.
        default: drop
      artifacts:
        type: string
        description: The path to the artifacts.
        default: "Artifacts/*.nupkg"
      release-title:
        type: string
        description: The title of the release.
        default: "Release"
        required: true
      release-notes:
        type: string
        description: The notes for the release.
        default: "Notes..."
        required: true
      artifactErrorsFailBuild:
        type: boolean
        description: Whether to fail the build if there are errors in the artifact.
        default: true

jobs:
  github-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.artifact-name }}
        path: Artifacts/

    - uses: ncipollo/release-action@main
      name: Create Release
      with:
        artifacts: ${{ inputs.artifacts }}
        artifactErrorsFailBuild: ${{ inputs.artifactErrorsFailBuild }}
        draft: true
        generateReleaseNotes: false
        name: release-title
        prerelease: true
